version: "3.7"

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shouzhi
    volumes:
      - $PWD/conf/my.cnf:/etc/my.cnf
      - $PWD/logs:/logs
      - $PWD/data:/var/lib/mysql
    container_name: mysql
    networks:
      - localnet
    ports:
      - 13306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password

networks:
  localnet:
    external:
      name: localnet